schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
jobs:
- template: ./.azure/azure-linux-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    os: linux

# - template: ./.azure/azure-osx-template.yml
#   parameters:
#     name: macOS
#     vmImage: macOS-10.13
#     os: osx

# - template: ./.azure/azure-windows-template.yml
#   parameters:
#    name: Windows
#    vmImage: vs2017-win2016
#    os: windows
